### ISSUE TITLE
react/jsx-no-bind

### ISSUE THREAD

**Issue by lukekarrys** [andyet/eslint-config-andyet-react#4]
This does a pretty good job of explaining why this rule exists and should arguably be used: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md#lists-of-items

The problem I've found is that its quite cumbersome to create a new class in order to not use an arrow fn, especially if you list item is very simple. I've never seen the performance implications of this either, so it feels a bit like premature optimization, but I have no data either way. It seems like a good rule in theory, which is why I added it originally, but I've found myself working around it multiple times now in ways I wish I didn't have to.

**Comment by latentflip** [comment]
I must admit I don't like it.

**Comment by latentflip** [comment]
So happy for it to go :)

**Comment by lukekarrys** [comment]
Removed :)
